CovidDataProject/Controllers/CovidDetailsController.cs
using CovidDataProject.Models;
using CovidDataProject.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CovidDataProject.Controllers
{
    public class CovidDetailsController : Controller
    {
        CovidService objCovidService = null;

        public CovidDetailsController()
        {
            objCovidService = new CovidService();
        }
        // GET: CovidDetails
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// Get Donut Chart Details
        /// </summary>
        /// <returns></returns>
        public JsonResult GetDonutChartDetails()
        {

            var res = objCovidService.GetCovidDonutDetails().Result;
            Int64 TotalConfimedCases = res.cases_time_series.Sum(dr => Convert.ToInt64(dr.totalconfirmed));
            Int64 TotalDeceasedCases = res.cases_time_series.Sum(dr => Convert.ToInt64(dr.totaldeceased));
            Int64 TotalRecoverdCases = res.cases_time_series.Sum(dr => Convert.ToInt64(dr.totalrecovered));


            var DictData = new Dictionary<string, Int64>() {
                { "TotalConfimedCases",TotalConfimedCases },
                { "TotalDeceasedCases",TotalDeceasedCases },
                { "TotalRecoverdCases",TotalRecoverdCases },
            };

            return Json(DictData, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Get State Wise Covid Details
        /// </summary>
        /// <returns></returns>
        public PartialViewResult GetCovidStateWiseDetails()
        {

            var ServiceResult = objCovidService.GetCovidStateWiseTabularDetails().Result;

            List<States_Daily> DataList = ServiceResult.states_daily
                            .GroupBy(c => c.status)
                            .Select(g => new States_Daily
                            {
                                status = g.Key,
                                an = g.Sum(c => Convert.ToInt64(c.an)).ToString(),
                                ap = g.Sum(c => Convert.ToInt64(c.ap)).ToString(),
                                ar = g.Sum(c => Convert.ToInt64(c.ar)).ToString(),
                                _as = g.Sum(c => Convert.ToInt64(c._as)).ToString(),
                                br = g.Sum(c => Convert.ToInt64(c.br)).ToString(),
                                ch = g.Sum(c => Convert.ToInt64(c.ch)).ToString(),
                                ct = g.Sum(c => Convert.ToInt64(c.ct)).ToString(),
                                dd = g.Sum(c => Convert.ToInt64(c.dd)).ToString(),
                                dl = g.Sum(c => Convert.ToInt64(c.dl)).ToString(),
                                dn = g.Sum(c => Convert.ToInt64(c.dn)).ToString(),
                                ga = g.Sum(c => Convert.ToInt64(c.ga)).ToString(),
                                gj = g.Sum(c => Convert.ToInt64(c.gj)).ToString(),
                                hp = g.Sum(c => Convert.ToInt64(c.hp)).ToString(),
                                hr = g.Sum(c => Convert.ToInt64(c.hr)).ToString(),
                                jh = g.Sum(c => Convert.ToInt64(c.jh)).ToString(),
                                jk = g.Sum(c => Convert.ToInt64(c.jk)).ToString(),
                                kl = g.Sum(c => Convert.ToInt64(c.kl)).ToString(),
                                la = g.Sum(c => Convert.ToInt64(c.la)).ToString(),
                                ld = g.Sum(c => Convert.ToInt64(c.ld)).ToString(),
                                mh = g.Sum(c => Convert.ToInt64(c.mh)).ToString(),
                                ml = g.Sum(c => Convert.ToInt64(c.ml)).ToString(),
                                mn = g.Sum(c => Convert.ToInt64(c.mn)).ToString(),
                                mp = g.Sum(c => Convert.ToInt64(c.mp)).ToString(),
                                mz = g.Sum(c => Convert.ToInt64(c.mz)).ToString(),
                                nl = g.Sum(c => Convert.ToInt64(c.nl)).ToString(),
                                or = g.Sum(c => Convert.ToInt64(c.or)).ToString(),
                                pb = g.Sum(c => Convert.ToInt64(c.pb)).ToString(),
                                py = g.Sum(c => Convert.ToInt64(c.py)).ToString(),
                                rj = g.Sum(c => Convert.ToInt64(c.rj)).ToString(),

                                sk = g.Sum(c => Convert.ToInt64(c.sk)).ToString(),
                                tg = g.Sum(c => Convert.ToInt64(c.tg)).ToString(),
                                tn = g.Sum(c => Convert.ToInt64(c.tn)).ToString(),
                                tr = g.Sum(c => Convert.ToInt64(c.tr)).ToString(),
                                tt = g.Sum(c => Convert.ToInt64(c.tt)).ToString(),
                                un = g.Sum(c => Convert.ToInt64(c.un)).ToString(),
                                up = g.Sum(c => Convert.ToInt64(c.up)).ToString(),
                                ut = g.Sum(c => Convert.ToInt64(c.ut)).ToString(),
                                wb = g.Sum(c => Convert.ToInt64(c.wb)).ToString(),

                            }).ToList();

            return PartialView("_TabularDataView",DataList);
        }
    }

}

CovidDataProject/Views/CovidDetails/Index.cshtml
@{
    Layout = null;
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- jQuery -->
<!-- FusionCharts -->
<script type="text/javascript" src="https://cdn.fusioncharts.com/fusioncharts/latest/fusioncharts.js"></script>
<!-- jQuery-FusionCharts -->
<script type="text/javascript" src="https://rawgit.com/fusioncharts/fusioncharts-jquery-plugin/develop/dist/fusioncharts.jqueryplugin.min.js"></script>
<!-- Fusion Theme -->
<script type="text/javascript" src="https://cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.fusion.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


<div>

    <div>
        <h2 style="text-align:center;margin-top:25px">Tabular Representation</h2>
        <div>
            @{Html.RenderAction("GetCovidStateWiseDetails"); }
        </div>
    </div>
    <div style="margin-top:25px;height:500px"> <div id="chart-container"></div></div>
</div>

<div class="text-right"><b>Made By : Shivam Saluja</b></div>
<script type="text/javascript">
$(document).ready(function(){
    GetDonutChartDetails();

 });
    /*************************** For Donut Chart ***************************/
    function GetDonutChartDetails() {

        $.ajax({
            'url': '@Url.Action("GetDonutChartDetails", "CovidDetails")',
            'type': 'GET',
            'success': function (data) {

                BindDonutChart(data);

            }
        });


    }


    function BindDonutChart(arr) {

        var donutdata = [];
        for (var key in arr) {
            donutdata.push({
                label: key,
                value: arr[key]
            });
        }
        
        $("#chart-container").insertFusionCharts({
            type: "doughnut2d",
            width: "100%",
            height: "100%",
            dataFormat: "json",
            dataSource: {
                chart: {
                    caption: "Donut Representation",
                   // showpercentvalues: "1",
                    defaultcenterlabel: "Covid-19  Cases",
                    aligncaptionwithcanvas: "0",
                    captionpadding: "0",
                    decimals: "1",
                    plottooltext:
                        "<b>$percentValue</b> of our Android users are on <b>$label</b>",
                    centerlabel: " $value",
                    theme: "fusion"
                },
                data: donutdata
            }
        });

    }


</script>

CovidDataProject/Views/CovidDetails/_TabularDataView.cshtml
@model IEnumerable<CovidDataProject.Models.States_Daily>
@{ 
    int SerialNo = 1;
}
<div class="table-responsive">
    <table cellspacing="2" cellpadding="2" border="1" class="table" style="border:1px solid black; width:100%">
        <thead>
            <tr>
                <th class="text-nowrap">Serial No.</th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.status)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.an)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.ap)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.ar)
                </th>
                
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.br)
                </th>
                <th class="text-center" >
                    @Html.DisplayNameFor(model => model.ch)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.ct)
                </th>
                
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.dd)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.dl)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.dn)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.ga)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.gj)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.hp)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.hr)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.jh)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.jk)
                </th>
               
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.kl)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.la)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.ld)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.mh)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.ml)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.mn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.mp)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.mz)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.nl)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.or)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.pb)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.py)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.rj)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.sk)
                </th>

                <th class="text-center">
                    @Html.DisplayNameFor(model => model.tg)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.tn)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.tr)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.tt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.un)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.up)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.ut)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.wb)
                </th>
               
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td class="text-center">@SerialNo</td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.status)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.an)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.ap)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.ar)
                </td>
               
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.br)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.ch)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.ct)
                </td>

                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.dd)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.dl)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.dn)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.ga)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.gj)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.hp)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.hr)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.jh)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.jk)
                </td>
                
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.kl)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.la)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.ld)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.mh)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.ml)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.mn)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.mp)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.mz)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.nl)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.or)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.pb)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.py)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.rj)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.sk)
                </td>

                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.tg)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.tn)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.tr)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.tt)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.un)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.up)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.ut)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.wb)
                </td>

            </tr>
                SerialNo++;
            }
        </tbody>
    </table>
</div>